name 'geogdog-hostnamefacts'
version '0.1.4'
source 'git://github.com/puppet/puppet-hostnamefacts.git'
author 'geogdog'
license 'Apache License, Version 2.0'
summary 'Provide some hostname facts for standardised hostname conventions'
description 'Provide some hostname facts for standardised hostname conventions'
project_page 'https://github.com/geogdog/puppet-hostnamefacts'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
